/* ---------------- factions/ranks: faction rank registry (pure data) ----------------
   Extracted from index.js. Per-faction rank order, display badges, and the
   Config/*.txt rank-file names. No logic and no bot state — just the data the
   faction rank helpers in index.js read. */
const FACTION_RANKS = {
  "NCR": {
    order:   ["Private", "Corporal", "Sergeant", "Medic", "Heavy", "Power Armor", "MP", "Ranger", "Lieutenant", "Officer"],
    default: "Private",
    badges:  {
      "Private":     "",
      "Corporal":    "",
      "Sergeant":    "",
      "Medic":       "",
      "Heavy":       "",
      "Power Armor": "",
      "MP":          "",
      "Ranger":      "",
      "Lieutenant":  "",
      "Officer":     "",
    },
    rankFiles: {
      "Private":     "ncrprivate.txt",
      "Corporal":    "ncrcorporal.txt",
      "Sergeant":    "ncrsergeant.txt",
      "Medic":       "ncrmedix.txt",
      "Heavy":       "ncrheavy.txt",
      "Power Armor": "ncrpowerarmor.txt",
      "MP":          "ncrmp.txt",
      "Ranger":      "ncrranger.txt",
      "Lieutenant":  "ncrlieutenant.txt",
      "Officer":    "ncrofficer.txt",
    },
  },
  "Legion": {
    order:   ["Recruit", "Legionnaire", "Explorer", "Slavemaster", "Prime Legionary", "Veteran Legionnaire", "Vexalarius", "Centurion", "Assassin", "Praetorian", "Legate"],
    default: "Recruit",
    badges:  {
      "Recruit":             "",
      "Legionnaire":         "",
      "Explorer":            "",
      "Slavemaster":         "",
      "Prime Legionary":     "",
      "Veteran Legionnaire": "",
      "Vexalarius":          "",
      "Centurion":           "",
      "Assassin":            "",
      "Praetorian":          "",
      "Legate":              "",
    },
    rankFiles: {
      "Recruit":             "legionrecruit.txt",
      "Legionnaire":         "legionlegionnaire.txt",
      "Explorer":            "legionexplorer.txt",
      "Slavemaster":         "legionslavemaster.txt",
      "Prime Legionary":     "legionprimelegionary.txt",
      "Veteran Legionnaire": "legionveteranlegionnaire.txt",
      "Vexalarius":          "legionvexalarius.txt",
      "Centurion":           "legioncenturion.txt",
      "Assassin":            "legionassasin.txt",
      "Praetorian":          "legionpraetorian.txt",
      "Legate":              "legionlegate.txt",
    },
  },
  "Enclave": {
    order:   ["Brigadeless", "Truth and Justice", "Research", "56th Rifle Brigade", "Recon", "Demolition", "Mechanized", "Hellfire", "Officer"],
    default: "Brigadeless",
    badges:  {
      "Brigadeless":        "",
      "Truth and Justice":  "",
      "Research":           "",
      "56th Rifle Brigade": "",
      "Recon":              "",
      "Demolition":         "",
      "Mechanized":         "",
      "Hellfire":           "",
      "Officer":            "",
    },
    rankFiles: {
      "Brigadeless":        "enclavebrigadeless.txt",
      "Truth and Justice":  "enclavetruthandjustice.txt",
      "Research":           "enclaveresearch.txt",
      "56th Rifle Brigade": "enclave56thriflebrigade.txt",
      "Recon":              "enclaverecon.txt",
      "Demolition":         "enclavedemolition.txt",
      "Mechanized":         "enclavemechanized.txt",
      "Hellfire":           "enclavehellfire.txt",
      "Officer":            "enclaveofficer.txt",
    },
  },
  "Khans": {
    order:   ["Prospect", "Enforcer", "Beserker", "Seargent", "Skirmisher", "Marksmen"],
    default: "Prospect",
    badges:  {
      "Prospect":   "",
      "Enforcer":   "",
      "Beserker":   "",
      "Seargent":   "",
      "Skirmisher": "",
      "Marksmen":   "",
    },
    rankFiles: {
      "Prospect":   "khansprospect.txt",
      "Enforcer":   "khansenforcer.txt",
      "Beserker":   "khansbeserker.txt",
      "Seargent":   "khansseargent.txt",
      "Skirmisher": "khansskirmisher.txt",
      "Marksmen":   "khansmarksmen.txt",
    },
  },
  "Brotherhood of Steel": {
    order:   ["Initiate", "Knight", "Paladin", "Elder"],
    default: "Initiate",
    badges:  {
      "Initiate": "",
      "Knight":   "",
      "Paladin":  "",
      "Elder":    "",
    },
    rankFiles: {
      "Initiate": "bosinitiate.txt",
      "Knight":   "bosknight.txt",
      "Paladin":  "bospaladin.txt",
      "Elder":    "boselder.txt",
    },
  },
  "Kings": {
    order:   ["Prospect", "Silver Ace", "Guard", "High Roller", "Crown", "The King"],
    default: "Prospect",
    badges:  {
      "Prospect":    "",
      "Silver Ace":  "",
      "Guard":       "",
      "High Roller": "",
      "Crown":       "",
      "The King":    "",
    },
    rankFiles: {
      "Prospect":    "kingsprospect.txt",
      "Silver Ace":  "kingssilverace.txt",
      "Guard":       "kingsguard.txt",
      "High Roller": "kingshighroller.txt",
      "Crown":       "kingscrown.txt",
      "The King":    "kingstheking.txt",
    },
  },
  "Super Mutants": {
    order:   ["Suicider", "Infantry", "Sergeant", "Nightkin", "Bombardier", "Behemoth"],
    default: "Suicider",
    badges:  {
      "Suicider":   "",
      "Infantry":   "",
      "Sergeant":   "",
      "Nightkin":   "",
      "Bombardier": "",
      "Behemoth":   "",
    },
    rankFiles: {
      "Suicider":   "supermutantsuicider.txt",
      "Infantry":   "supermutantinfantry.txt",
      "Sergeant":   "supermutantsergeant.txt",
      "Nightkin":   "supermutantnightkin.txt",
      "Bombardier": "supermutantbombardier.txt",
      "Behemoth":   "supermutantbehemoth.txt",
    },
  },
  "Followers": {
    order:   ["Follower", "Guard", "Recruit", "Scholar", "Director"],
    default: "Follower",
    badges:  {
      "Follower": "",
      "Guard":    "",
      "Recruit":  "",
      "Scholar":  "",
      "Director": "",
    },
    rankFiles: {
      "Follower": "followersfollower.txt",
      "Guard":    "followersguard.txt",
      "Recruit":  "followersrecruit.txt",
      "Scholar":  "followersscholar.txt",
      "Director": "followersdirector.txt",
    },
  },
};

module.exports = { FACTION_RANKS };
